Para utilizar o `numpy` foi adicionado um kernel com um ambiente virtual do conda conforme [7].

In [1]:
import numpy as np # Uma convenção para `numpy` é chamar ela de `np`.

### Criando Arrays

In [2]:
minha_lista = [1, 2, 3]
minha_lista

[1, 2, 3]

In [3]:
np.array(minha_lista) # Cria um `numpy array` de uma dimensão.

array([1, 2, 3])

In [4]:
# Agora temos uma lista de listas que caracteriza duas dimensões, ou seja uma matriz.
minha_matriz = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]

In [5]:
np.array(minha_matriz) # Mostra uma matriz (note os dois colchetes)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Métodos `numpy` para criação de séries e matrizes

In [6]:
# shift + tab para observar documentação do método.
np.arange(0, 10) # Cria uma sequência de números, semelhante ao `range` do python. Note o último elemento não incluso.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2) # 2 é o `step`, neste caso de dois em dois.

array([0, 2, 4, 6, 8])

In [8]:
arr = np.zeros(3) # Cria uma matriz com elementos zerados
arr

array([0., 0., 0.])

In [9]:
arr = np.zeros((5, 5)) # Cria uma matriz 5x5 com todos os elementos zerados.
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3, 3)) # Cria uma matriz 3x3 prenchida por números um.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(4) # Cria uma matriz identidade 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.linspace(0, 10, 3) # Cria uma série em que os itens dentro do intervalo são igualmente espaçados. 
                        # Os números são definidos pelo terceiro parametro, no caso três números dentro da série.

array([ 0.,  5., 10.])

In [13]:
# a sub biblioteca `random` do `numpy` cria séries ou matrizes aleatórias com regras diferentes.

np.random.rand(5) # Escolhe 5 números aleatórios entre 0 e 1 com igual probabilidade de ser selecionado (distribuição uniforme).

array([0.1857925 , 0.39356054, 0.2711854 , 0.06816654, 0.12786347])

In [14]:
np.random.rand(5) * 100 # Agora são números de 0 a 100 por conta do `* 100`.

array([87.28037348, 91.92416747, 95.72899196, 80.06550182, 93.92589406])

In [15]:
np.random.rand(5, 4) # Cria uma matriz 5x4 com valores aleatórios entre 0 e 1.

array([[0.51993782, 0.21768732, 0.18318534, 0.78473257],
       [0.78577171, 0.3150029 , 0.78868252, 0.18286466],
       [0.22633934, 0.82920447, 0.98081497, 0.66203811],
       [0.38791404, 0.10231003, 0.69208938, 0.61019543],
       [0.29812282, 0.9102813 , 0.54838463, 0.92681206]])

In [16]:
np.random.rand(5, 4, 3) # Uma matriz de 3 dimensões.

array([[[0.23167712, 0.72983992, 0.23247897],
        [0.57096303, 0.38657176, 0.88069871],
        [0.39222138, 0.19948162, 0.95986688],
        [0.69736434, 0.65064171, 0.01876202]],

       [[0.73704949, 0.68230358, 0.88401698],
        [0.66932612, 0.47443919, 0.03482893],
        [0.11966282, 0.94087778, 0.08482267],
        [0.87236091, 0.16742075, 0.34911755]],

       [[0.20188478, 0.3055592 , 0.0536012 ],
        [0.75346278, 0.25048576, 0.29299497],
        [0.29406447, 0.27359712, 0.87403404],
        [0.81275129, 0.63046053, 0.33440445]],

       [[0.45787193, 0.83675186, 0.63026455],
        [0.37472525, 0.89518569, 0.66726692],
        [0.93914131, 0.5961719 , 0.3919584 ],
        [0.49167857, 0.14606765, 0.27339946]],

       [[0.22904657, 0.03063961, 0.3888402 ],
        [0.35830223, 0.26589074, 0.59670484],
        [0.69355756, 0.33689698, 0.09339659],
        [0.48144699, 0.09640318, 0.69381956]]])

In [17]:
np.random.randn(4) # `randn` utiliza uma distribuição normal com média 0 e desvio padrão 1 (Gaussiana) 
                    # sendo está mais aplicada na prática, se ennquadra em uma séries de amostras que
                    # são mais relevantes que uma distribuição uniforme.

array([ 0.74361208, -0.36202206,  1.70561081,  1.07058593])

In [18]:
np.random.randint(0, 100, 10) # Uma série de números inteiros dentro de um intervalo de uma distribuição aleatória.
                                # Números entre [0, 10 [ (10 não incluso)

array([99, 88, 16, 82, 37, 39, 60, 49, 11, 60])

In [19]:
np.round(np.random.rand(5) * 100, 0) # Equivalente ao `randint` acima utilizando o `round` que recebe uma série
                                        # e arredonda, o segundo parâmetro é a quantidade de casas depois da
                                        # vírgula, no caso 0. 

array([43., 19., 49., 39., 90.])

### Métodos e atributos

In [21]:
# Reshape

arr = np.random.rand(25)
arr # vetor de 25 elementos

array([0.92947456, 0.04004044, 0.38274163, 0.39256816, 0.82025553,
       0.6458784 , 0.32220543, 0.72454102, 0.60221651, 0.09626748,
       0.83997322, 0.14051452, 0.55751896, 0.61942406, 0.76163845,
       0.46735673, 0.07320111, 0.97853146, 0.73638872, 0.0272706 ,
       0.13554982, 0.82251701, 0.85229798, 0.4888759 , 0.78465247])

In [24]:
arr.reshape((5, 5)) # Neste caso cria instancia uma nova série, sendo uma matriz 5x5
                        # A váriave `arr` não é sobreescrita apenas se for reatribuída (utilizando `=`)

array([[0.92947456, 0.04004044, 0.38274163, 0.39256816, 0.82025553],
       [0.6458784 , 0.32220543, 0.72454102, 0.60221651, 0.09626748],
       [0.83997322, 0.14051452, 0.55751896, 0.61942406, 0.76163845],
       [0.46735673, 0.07320111, 0.97853146, 0.73638872, 0.0272706 ],
       [0.13554982, 0.82251701, 0.85229798, 0.4888759 , 0.78465247]])

In [26]:
arr = arr.reshape((5, 5)) # `arr` reatribuído
arr

array([[0.92947456, 0.04004044, 0.38274163, 0.39256816, 0.82025553],
       [0.6458784 , 0.32220543, 0.72454102, 0.60221651, 0.09626748],
       [0.83997322, 0.14051452, 0.55751896, 0.61942406, 0.76163845],
       [0.46735673, 0.07320111, 0.97853146, 0.73638872, 0.0272706 ],
       [0.13554982, 0.82251701, 0.85229798, 0.4888759 , 0.78465247]])

In [27]:
arr.shape # mostra o tamanho do array numpy

(5, 5)

In [29]:
arr.max() # retorna o maior valor dentro do array numpy

np.float64(0.9785314610912139)

In [30]:
arr.min() # retorna o menor valor dentro do array numpy

np.float64(0.027270596714208617)

In [31]:
arr.argmax() # retorna o índice na qual o maior elemento se encontra

np.int64(17)

In [34]:
arr.argmin() # retorna o índice na qual o menor elemento se encontra

np.int64(19)