In [9]:
import numpy as np

### Acessando elementos através do índice e fatiando `arrays numpy`.

In [2]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
arr[3] # Os valores do `numpy array` podem ser acessados através do indíce

np.int64(9)

In [4]:
arr[2:5] # Traz os elementos no intervalo [2, 5[ ou seja, nos indíces 2, 3 e 4 (note o 5 não incluso)

array([ 6,  9, 12])

In [5]:
arr[:5] # Nada antes dos `:` entende que começa no 0 o intervalo [0, 1, 2, 3, 4]

array([ 0,  3,  6,  9, 12])

In [6]:
arr[2:] # Nada após `:` entende que vai até o fim do array o final do intervalo

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
arr[2:] = 100 # Podemos fazer a manipulação (no caso atribuição) através dos `arrays` recuperados.
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

### Indíce e fatia (_slice_) em `arrays` bidimensionais

In [15]:
arr = np.arange(50).reshape((5, 10)) # Uma matriz 5x10
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [16]:
arr.shape

(5, 10)

In [19]:
# Notações de dois colchetes ou um colchete, sendo a de um mais simples
arr[:3][:] # [:3] Fatia as linhas da matriz, e em seguida [:] traz todas as colunas
            # Como utiliza [:] seria o equivalente a: `arr[:3]`

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [40]:
arr[:2, 3:9] # Para fazer o slice da segunda dimensão separa os `slices` por `,` conforme a documentação do NumPy [8]
                # Neste caso fatia as duas primeiras linhas (indíce 0 e 1) em seguida as colunas no intervalo de [3, 9[.
                # Havia pausado a aula para pesquisar como fazer mas em seguida na aula essa abordagem é tratada.

array([[ 3,  4,  5,  6,  7,  8],
       [13, 14, 15, 16, 17, 18]])

In [42]:
# Fatia o array, fazendo uma referência. 
arr2 = arr[:3]
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [47]:
arr2[:] = 100 # Essa atribuição afeta a matriz em `arr` pois arr2 é uma referência (aponta para) 
                # dos elementos do array.
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [48]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [49]:
arr = np.arange(50).reshape((5, 10)) # Reinicializando o `arr`
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr2 = arr[:3].copy() # ao utilizar o `copy` os elementos armazenados em `arr2` agora não são mais uma
                        # referência dos elementos em `arr` e sim uma cópia que referência novos elementos
                        # e não mais aponta para outro `array`.
arr2[:] = 100
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [55]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
arr[1:4, 5:] # Uma fatia de 3 linhas e 5 colunas
                # Primeira dimensão [1, 4[ (linhas)
                # Segunda dimensão [5, ...[ (colunas)

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

### Operações em `array numpy`

In [66]:
arr2 = arr[:3]
arr2[:] = 100 # Para seguir com exemplo da aula

bol = arr > 50 # Retorna resultados da operação booleana para cada elemento do `array`.
bol

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [69]:
arr[bol] # Podemos utilizar o resultado da operação lógica como indíce onde serão retornados apenas 
            # os elementos que são verdadeiros dentro do `array numpy`.

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

### Outros exemplos

In [71]:
array = np.linspace(0, 100, 30)
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [72]:
array = array.reshape(3, 10) # A multiplicação dos elementos deve ser igual a quantidade de elementos
                                # atuais ao fazer o `reshape` para que possam ser distribuídos.
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [74]:
array.shape

(3, 10)

In [75]:
array[0:2, 2] # No caso queremos acessar os valores da terceira coluna (

array([ 6.89655172, 41.37931034])