In [1]:
import numpy as np

### Operações Aritméticas entre `arrays`.

In [2]:
arr = np.arange(0, 16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
arr + arr # Operação de soma indíce por indíce, importante ambos terem o mesmo tamanho.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [6]:
arr / arr # Neste caso de divisão incorreta há um aviso (`RuntimeWarning`), neste caso a operação retorna `nan`

/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_91145/705767208.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr # Neste caso de divisão incorreta há um aviso (`RuntimeWarning`), neste caso a operação retorna `nan`


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [7]:
1 / arr # Neste caso retorno um infinito definido por `inf`. 

/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_91145/525996509.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # Neste caso retorno um infinito definido por `inf`.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [8]:
np.array([0, 1]) / 0 # Ambas as mensagens onde 0 / 0 resulta em `nan` e 1 / 0 resulta em `inf`.

/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_91145/2327825245.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1]) / 0 # Ambas as mensagens onde 0 / 0 resulta em `nan` e 1 / 0 resulta em `inf`.
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_91145/2327825245.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1]) / 0 # Ambas as mensagens onde 0 / 0 resulta em `nan` e 1 / 0 resulta em `inf`.


array([nan, inf])

In [9]:
arr ** 2 # Também pode ser fazer exponenciação.

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

### Operações com escalares

In [10]:
arr + 100 # Soma 100 a todos os elementos do `array`.  

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [11]:
arr * 30 # Operações aplicadas a todos os elementos do array.

array([  0,  30,  60,  90, 120, 150, 180, 210, 240, 270, 300, 330, 360,
       390, 420, 450])

### Métodos do NumPy.

In [12]:
np.sqrt(arr) # `sqrt` aplica a raiz quadrada para todos os elementos

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [13]:
np.exp(arr) # `exp` aplica exponenciação a todos os elementos do `array`.

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [14]:
np.mean(arr) # `mean` para saber a média do `array`

np.float64(7.5)

In [15]:
np.std(arr) # `std` para saber o desvio padrão (standard deviation) do `array`

np.float64(4.6097722286464435)

In [16]:
np.sin(arr) # `sin` traz o seno de cada elemento.

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [17]:
np.max(arr) # `max` traz o valor máximo do `array`.

np.int64(15)

In [18]:
np.min(arr) # `min` traz o valor mínimo do `array`.

np.int64(0)

In [19]:
arr.max() # pode também ser utilizado para retornar o valor máximo

np.int64(15)

In [20]:
arr.min() # pode também ser utilizado para retornar o valor mínimo

np.int64(0)