# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

#### Importe NumPy como np

In [1]:
import numpy as np

#### Crie uma matriz de 10 zeros

In [6]:
# Utilizar `zeros` do `np` passando 10
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Crie uma matriz de 10 ones

In [7]:
# Utilizar `zeros` do `np` passando 10
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Crie uma matriz de 10 cincos

In [9]:
# Criar uma matriz com uns e então multiplicá-la por 5 onde a operação é feita elemento por elemento.
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Crie um array de inteiros de 10 até 50

In [10]:
# Utilizar `arange` que cria um arranjo (`array`) passando o início do 
# intervalo como 10 e o fim como 51, uma vez que o fim do intervalo 
# não é incluso.
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crie um array dos numeros pares de 10 até 50

In [15]:
# Criar o `array` utilizando o `arange` pulando de dois em dois através
# do terceiro parâmetro `step`. Assim começa com um número par (10) e 
# termina em par.
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Criei uma matriz 3x3 com valores variando de 0 até 8

In [16]:
# Criar uma vetor de 0 a 9 (não inclusivo), e utilizar o `reshape` tranformando em uma 
# matriz 3x3 com o parâmetro (3, 3).
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crie uma matriz identidade 3x3

In [17]:
# Para criar a matriz identidade podemos utilizar `eye` informando o número de linhas e colunas 
# no caso 3. 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy para gerar números aleatórios entre 0 e 1

In [19]:
# Utilizar o sub módulo `random` do NumPy, nele há a função `rand` que recebe quantos
# número serão gerados (o shape separado por vírgula conforme a documentação e a 
# quantidade de elementos), no caso uma dimensão com um elemento.
np.random.rand(1)

array([0.3313661])

array([ 0.42829726])

#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [21]:
# Para a distribuição normal utiliza-se a função `randn` do NumPy que também 
# está no módulo `random`.
np.random.randn(25)

array([ 1.71269239, -0.75812815, -0.07352454, -0.34068833, -2.56296425,
        0.51830386, -0.23438732,  0.03789926,  1.8844421 ,  0.47905319,
        0.88929571, -0.57119977,  1.22303804,  0.67424241,  0.73333188,
        0.1825236 ,  0.48284217, -1.45372922, -0.8796602 , -0.6532586 ,
       -2.70243847,  0.50958394, -0.6119101 ,  0.53087012,  0.15410561])

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Crie a seguinte matriz:

In [58]:
# A forma proposta na aula de solução difere, utilizou-se:
# np.arange(0, 101) / 100

# A seguinte matriz é uma matriz 10x10 onde os elementos estão entre 0 e 1 
# com intervalo de 0.01 entre cada elemento. Para isso cria-se um intervalo
# entre 0.01 e 1.01 (1 incluso) onde é incrementado em 0.01 cada elemento
# por fim altera o formato do arranjo para uma matriz 10x10 utilizando 
# `reshape`.
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [26]:
# Para criar arranjos igualmente espaçados utiliza-se a função `linspace` do NumPy, onde:
# 0 é o início do intervalo e 1 o fim do intervalo (inclusivo) e 20 é a quantidade de 
# elementos igualmente espaçados.
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [27]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
# ESCREVE O CÓDIGO AQUI

# Fatiar as últimas 3 linhas, trazendo todas às colunas com exceção da primeira.
# Começar na 3 linha (indíce 2) e na segunda coluna (indíce 1).
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [35]:
# ESCREVE O CÓDIGO AQUI 
# 20 é o elemento que se encontra na quarta linha (indíce 3) na quinta coluna (indíce 4)
mat[3, 4]

np.int64(20)

20

In [41]:
# ESCREVE O CÓDIGO AQUI 
# Trazer apenas os elementos das 3 primeiras linhas (indíces 0, 1, 2) na segunda coluna (indíce 1)
# obs: se utilizar [:3, 1] na indexação irá retornar um vetor ao invés de matriz.
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [42]:
# ESCREVE O CÓDIGO AQUI 
# Retornar a quinta linha (última) da matriz, para o último elemento podemos utilizar `-1` como indíce.
mat[-1]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [44]:
# ESCREVE O CÓDIGO AQUI 
# Retornar as duas últimas linhas da matriz, agora utilizando a fatia `-2:` como indíce.
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [47]:
mat.sum() # `sum` traz a soma de todos os valores da matriz

np.int64(325)

325

#### Obter o desvio padrão dos valores em mat

In [48]:
# Para trazer o desvio padrão utilizar o `std`.
mat.std()

np.float64(7.211102550927978)

7.2111025509279782

#### Obter a soma de todas as colunas em mat

In [56]:
mat.sum(0) # Conforme a documentação em [9] podemos somar os valores com base na `axis` (eixo) 
            # sendo 0 o eixo que opera a soma entre os elementos de cada coluna.

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])